services:
  amigo-api:
    image: ghcr.io/mayyzenacs/amigo-api:latest
    container_name: amigo-api
    restart: unless-stopped
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - DOTNET_gcServer=0
      - DOTNET_ThreadPool__MinThreads=2
      - DOTNET_ThreadPool__MaxThreads=15
    volumes:
      - ./data:/app/data
    env_file:
      - .env
    networks:
      - main_network

    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  amigo-web:
    image: ghcr.io/mayyzenacs/amigo-web:latest
    container_name: amigo-web
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      - amigo-api
    networks:
      - main_network

    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  main_network:
    external: true
