services:
  amigo-api-local:
    build:
      context: ./AmigoNcompra_api
      dockerfile: dockerfile
    container_name: amigo-api-dev
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - DOTNET_gcServer=0
      - DOTNET_ThreadPool__MinThreads=2
      - DOTNET_ThreadPool__MaxThreads=15
    volumes:
      - ./data:/app/data
