FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build
WORKDIR /src

COPY ["AmigoNcompra-api.csproj", "./"]
RUN dotnet restore "AmigoNcompra-api.csproj"

COPY . .

RUN dotnet publish "AmigoNcompra-api.csproj" -c Release -o /app/publish /p:UseAppHost=false

FROM mcr.microsoft.com/dotnet/aspnet:10.0-alpine AS final
WORKDIR /app

RUN apk add --no-cache icu-libs tzdata
ENV DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=false
ENV TZ=America/Sao_Paulo

ENV ASPNETCORE_HTTP_PORTS=8080
EXPOSE 8080

COPY --from=build /app/publish .

RUN mkdir -p /app/data && chown -R app:app /app/data

USER app

ENTRYPOINT ["dotnet", "AmigoNcompra-api.dll"]