FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build
WORKDIR /src

COPY ["AmigoNcompra-api.csproj", "./"]
RUN dotnet restore "AmigoNcompra-api.csproj"

COPY . .

RUN dotnet publish "AmigoNcompra-api.csproj" -c Release -o /app/publish /p:UseAppHost=false

FROM mcr.microsoft.com/dotnet/aspnet:10.0
WORKDIR /app
ENV DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=1

COPY --from=build /app/publish .

RUN mkdir -p /app/data

EXPOSE 80

ENTRYPOINT ["dotnet", "AmigoNcompra-api.dll"]